name: Docker Image CI

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Generate timestamp
      id: ts
      run: echo "value=$(date -u +'%Y%m%d%H%M%S')" >> "$GITHUB_OUTPUT"

    - name: Build and Push
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/k8s-labs-user-service:latest
          ${{ secrets.DOCKERHUB_USERNAME }}/k8s-labs-user-service:${{ github.sha }}
          ${{ secrets.DOCKERHUB_USERNAME }}/k8s-labs-user-service:${{ steps.ts.outputs.value }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
